language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO="django==1.6.5"
  - DJANGO="django==1.5.8"
  - DJANGO="django==1.4.13"
  - DJANGO="django==1.3.7"

install:
  - pip install $DJANGO
  - pip install djangorestframework django-nose --use-mirrors
  - export PYTHONPATH=.

script:
  - python rest_expiration_token/runtests/runtests.py


matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="https://www.djangoproject.com/download/1.7.b4/tarball/"
    - python: "3.2"
      env: DJANGO="django==1.4.13"
    - python: "3.2"
      env: DJANGO="django==1.3.7"
    - python: "3.3"
      env: DJANGO="django==1.4.13"
    - python: "3.3"
      env: DJANGO="django==1.3.7"
    - python: "3.4"
      env: DJANGO="django==1.4.13"
    - python: "3.4"
      env: DJANGO="django==1.3.7"