language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"

env:
  - DJANGO="django==1.6.5 --use-mirrors"
  - DJANGO="django==1.5.8 --use-mirrors"

install:
  - pip install $DJANGO
  - pip install djangorestframework django-nose --use-mirrors
  - export PYTHONPATH=.

script:
  - python rest_expired_token/runtests/runtests.py